name: Build and Push Docker Images

on:
  push:
    branches:
      - main  

jobs:
  build :
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'  
        run: |
          echo "Logging in to Amazon ECR..."
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build and Push Backend Docker Image to ecr
        run: |
          echo "Building the Backend Docker image"
          docker build -t ${{ secrets.ECR_REGISTRY }}:latest-backend -f ./backend .
          echo "Pushing the Backend Docker image to Amazon ECR"
          docker push ${{ secrets.ECR_REGISTRY }}:latest-backend

      - name: Build and Push Frontend Docker Image to ecr
        run: |
          echo "Building the Frontend Docker image"
          docker build -t ${{ secrets.ECR_REGISTRY }}:latest-frontend -f ./frontend .
          echo "Pushing the Frontend Docker image to Amazon ECR"
          docker push ${{ secrets.ECR_REGISTRY }}:latest-frontend
