name: Build and Push Docker Images

on:
  push:
    branches:
      - main  

jobs:
  build :
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'  
        run: |
          echo "Logging in to Amazon ECR..."
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build and Push Backend Docker Image to ecr
        run: |
          echo "Building the Backend Docker image"
          cd ./backend
          docker build -t ${{ secrets.ECR_REGISTRY }}:latest-backend -f ./Dockerfile .
          echo "Pushing the Backend Docker image to Amazon ECR"
          docker push ${{ secrets.ECR_REGISTRY }}:latest-backend

      - name: Introducing the new image ID in the Amazon ECS task definition 
        id: backend-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
           task-definition: ./backend/task-definition.json
           container-name: mern-backend
           image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
           task-definition: ${{ steps.task-def.outputs.task-definition }}
           service: my-backend-service
           cluster: my-ECSCluster
           wait-for-service-stability: true

      

      - name: Build and Push Frontend Docker Image to ecr
        run: |
          echo "Building the Frontend Docker image"
          cd ./frontend
          docker build -t ${{ secrets.ECR_REGISTRY }}:latest-frontend -f ./Dockerfile .
          echo "Pushing the Frontend Docker image to Amazon ECR"
          docker push ${{ secrets.ECR_REGISTRY }}:latest-frontend

      - name: Introducing the new image ID for the frontend in the Amazon ECS task definition 
        id: frontend-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
           task-definition: ./frontend/task-definition.json
           container-name: mern-frontend
           image: ${{ steps.build-image.outputs.image }}
          
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
           task-definition: ${{ steps.task-def.outputs.task-definition }}
           service: my-frontend-service
           cluster: my-ECSCluster
           wait-for-service-stability: true

      

      
